//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSchool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] aspose_total {
            get {
                object obj = ResourceManager.GetObject("aspose_total", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap balance_ok_128 {
            get {
                object obj = ResourceManager.GetObject("balance_ok_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cabinet_info_128 {
            get {
                object obj = ResourceManager.GetObject("cabinet_info_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;課程系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;所屬班級&quot; /&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」必須有資料。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」長度必須小於300個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字300&quot;  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CourseBulkProcessValidateFieldRule {
            get {
                return ResourceManager.GetString("CourseBulkProcessValidateFieldRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap expandableButtonImageCollapse {
            get {
                object obj = ResourceManager.GetObject("expandableButtonImageCollapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap expandableButtonImageExpand {
            get {
                object obj = ResourceManager.GetObject("expandableButtonImageExpand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FeatureDefinition&gt;
        ///  &lt;FeatureCatalog Path=&quot;學生/功能按鈕&quot; AccessOptions=&quot;Execute,None&quot;&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0010&quot; Title=&quot;新增學生&quot;/&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0020&quot; Title=&quot;儲存學生&quot;/&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0030&quot; Title=&quot;刪除學生&quot; Color=&quot;Red&quot;/&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0085&quot; Title=&quot;德行成績&quot;/&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0040&quot; Title=&quot;計算成績&quot;/&gt;
        ///    &lt;ButtonItem FeatureCode=&quot;Button0050&quot; Title=&quot;排名&quot;/&gt;
        ///    &lt;!--&lt;ButtonItem FeatureCode=&quot;Button0060&quot; Title=&quot;獎勵&quot; Color=&quot;yellow&quot;/&gt;
        ///  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string FeatureDefinition {
            get {
                return ResourceManager.GetString("FeatureDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap foreign_key_lock_64 {
            get {
                object obj = ResourceManager.GetObject("foreign_key_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading5 {
            get {
                object obj = ResourceManager.GetObject("loading5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap LoginLogo {
            get {
                object obj = ResourceManager.GetObject("LoginLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap mail_ok_64 {
            get {
                object obj = ResourceManager.GetObject("mail_ok_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Mark2 {
            get {
                object obj = ResourceManager.GetObject("Mark2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap school_fav_64 {
            get {
                object obj = ResourceManager.GetObject("school_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///	&lt;Field InternalName=&quot;CourseID&quot; Name=&quot;課程系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot; /&gt;
        ///	&lt;Field InternalName=&quot;ClassName&quot; Name=&quot;所屬班級&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;CourseName&quot; Name=&quot;課程名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;SemesterUnique&quot; /&gt;
        ///  &lt;Field InternalName=&quot;Domain&quot; Name=&quot;領域&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field InternalName=&quot;SubjectName&quot; Name=&quot;科目名稱&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InternalName=&quot;SubjectLevel&quot; Name=&quot;科目級別&quot; ShiftCheckable=&quot;Tr [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_Course_ImportFieldList {
            get {
                return ResourceManager.GetString("SH_Course_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap SmartLogo拷貝 {
            get {
                object obj = ResourceManager.GetObject("SmartLogo拷貝", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap speech_balloon_64 {
            get {
                object obj = ResourceManager.GetObject("speech_balloon_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap spiral_lock_64 {
            get {
                object obj = ResourceManager.GetObject("spiral_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap world_upload_64 {
            get {
                object obj = ResourceManager.GetObject("world_upload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 偷來改的齒輪 {
            get {
                object obj = ResourceManager.GetObject("偷來改的齒輪", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 寬箭頭 {
            get {
                object obj = ResourceManager.GetObject("寬箭頭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 寬箭頭陰影 {
            get {
                object obj = ResourceManager.GetObject("寬箭頭陰影", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 紅箭頭 {
            get {
                object obj = ResourceManager.GetObject("紅箭頭", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
