//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSchool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap admin_64 {
            get {
                object obj = ResourceManager.GetObject("admin_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnAddCourse_image {
            get {
                object obj = ResourceManager.GetObject("btnAddCourse_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnremoveCourse_image {
            get {
                object obj = ResourceManager.GetObject("btnremoveCourse_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;課程系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;數字最大極限&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;所屬班級&quot; /&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」必須有資料。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」長度必須小於300個文字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;文字300&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CourseBulkProcessValidateFieldRule {
            get {
                return ResourceManager.GetString("CourseBulkProcessValidateFieldRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("folder_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_64 {
            get {
                object obj = ResourceManager.GetObject("group_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading5 {
            get {
                object obj = ResourceManager.GetObject("loading5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meeting_refresh_64 {
            get {
                object obj = ResourceManager.GetObject("meeting_refresh_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_Course_New {
            get {
                object obj = ResourceManager.GetObject("Navigation_Course_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap network_lock_64 {
            get {
                object obj = ResourceManager.GetObject("network_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;課程系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;課程名稱&quot; Name=&quot;CourseName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;領域&quot; Name=&quot;Domain&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DataType=&quot;integer&quot; DisplayText=&quot;科目級別&quot; Name=&quot;SubjectLevel&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;科目名稱&quot; Name=&quot;Subject&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;所屬班級&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field DisplayText=&quot;學年度&quot; Name=&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SH_Course_ExportDescription {
            get {
                return ResourceManager.GetString("SH_Course_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FieldDescription&gt;
        ///	&lt;Field InternalName=&quot;CourseID&quot; Name=&quot;課程系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot; /&gt;
        ///	&lt;Field InternalName=&quot;ClassName&quot; Name=&quot;所屬班級&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;CourseName&quot; Name=&quot;課程名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;SemesterUnique&quot; /&gt;
        ///	&lt;Field InternalName=&quot;SubjectName&quot; Name=&quot;科目名稱&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InternalName=&quot;SubjectLevel&quot; Name=&quot;科目級別&quot; ShiftCheckable=&quot;True&quot; /&gt;
        ///	&lt;Field InternalName=&quot;ScoreType&quot; Name=&quot;分項類別&quot; ShiftCheckabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SH_Course_ImportFieldList {
            get {
                return ResourceManager.GetString("SH_Course_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 課程修課學生清單 {
            get {
                object obj = ResourceManager.GetObject("課程修課學生清單", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
