//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSchool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap administrator_add_64 {
            get {
                object obj = ResourceManager.GetObject("administrator_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap administrator_remove_64 {
            get {
                object obj = ResourceManager.GetObject("administrator_remove_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnaddclass_image {
            get {
                object obj = ResourceManager.GetObject("btnaddclass_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnaddstudent_image {
            get {
                object obj = ResourceManager.GetObject("btnaddstudent_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnaddteacher_image {
            get {
                object obj = ResourceManager.GetObject("btnaddteacher_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btndeleteclass_image {
            get {
                object obj = ResourceManager.GetObject("btndeleteclass_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btndeletestudent_image {
            get {
                object obj = ResourceManager.GetObject("btndeletestudent_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btndeleteteacher_image {
            get {
                object obj = ResourceManager.GetObject("btndeleteteacher_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap college_write_64 {
            get {
                object obj = ResourceManager.GetObject("college_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;GetCountyTownBelong&gt;
        ///  &lt;Town Code=&quot;100&quot; County=&quot;臺北市&quot; Name=&quot;中正區&quot; /&gt;
        ///  &lt;Town Code=&quot;103&quot; County=&quot;臺北市&quot; Name=&quot;大同區&quot; /&gt;
        ///  &lt;Town Code=&quot;104&quot; County=&quot;臺北市&quot; Name=&quot;中山區&quot; /&gt;
        ///  &lt;Town Code=&quot;105&quot; County=&quot;臺北市&quot; Name=&quot;松山區&quot; /&gt;
        ///  &lt;Town Code=&quot;106&quot; County=&quot;臺北市&quot; Name=&quot;大安區&quot; /&gt;
        ///  &lt;Town Code=&quot;108&quot; County=&quot;臺北市&quot; Name=&quot;萬華區&quot; /&gt;
        ///  &lt;Town Code=&quot;110&quot; County=&quot;臺北市&quot; Name=&quot;信義區&quot; /&gt;
        ///  &lt;Town Code=&quot;111&quot; County=&quot;臺北市&quot; Name=&quot;士林區&quot; /&gt;
        ///  &lt;Town Code=&quot;112&quot; County=&quot;臺北市&quot; Name=&quot;北投區&quot; /&gt;
        ///  &lt;Town Code=&quot;114&quot; County= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CountyTownBelong {
            get {
                return ResourceManager.GetString("CountyTownBelong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ctxTag_Image {
            get {
                object obj = ResourceManager.GetObject("ctxTag_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap DefaultSearchImage {
            get {
                object obj = ResourceManager.GetObject("DefaultSearchImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Export_Image {
            get {
                object obj = ResourceManager.GetObject("Export_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("folder_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] GMapContainer {
            get {
                object obj = ResourceManager.GetObject("GMapContainer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap graduated_write_64 {
            get {
                object obj = ResourceManager.GetObject("graduated_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon info_ico {
            get {
                object obj = ResourceManager.GetObject("info_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon Info3D {
            get {
                object obj = ResourceManager.GetObject("Info3D", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] InfoWindow {
            get {
                object obj = ResourceManager.GetObject("InfoWindow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading5 {
            get {
                object obj = ResourceManager.GetObject("loading5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap locked {
            get {
                object obj = ResourceManager.GetObject("locked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MapFemale {
            get {
                object obj = ResourceManager.GetObject("MapFemale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap MapMale {
            get {
                object obj = ResourceManager.GetObject("MapMale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_Class_New {
            get {
                object obj = ResourceManager.GetObject("Navigation_Class_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_Student_New {
            get {
                object obj = ResourceManager.GetObject("Navigation_Student_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Navigation_Teacher_New {
            get {
                object obj = ResourceManager.GetObject("Navigation_Teacher_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap network_lock_64 {
            get {
                object obj = ResourceManager.GetObject("network_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap notepad_lock_64 {
            get {
                object obj = ResourceManager.GetObject("notepad_lock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap paste_64 {
            get {
                object obj = ResourceManager.GetObject("paste_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap refresh_window_64 {
            get {
                object obj = ResourceManager.GetObject("refresh_window_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sandglass_unlock_64 {
            get {
                object obj = ResourceManager.GetObject("sandglass_unlock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;班級系統編號&quot; Name=&quot;ID&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;班級名稱&quot; Name=&quot;ClassName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;班導師&quot; Name=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;年級&quot; Name=&quot;GradeYear&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;科別&quot; Name=&quot;DepartmentName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;課程規劃&quot; Name=&quot;GraduationPlan&quot;/&gt;	
        ///  &lt;Field DisplayText=&quot;計算規則&quot; Name=&quot;CalculationRule&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;排列序號&quot; Name=&quot;DisplayOrder&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;班級名稱規則&quot; Name=&quot;NamingRule&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;班級編號&quot; Name=&quot;ClassNumber [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_Cls_ExportDescription {
            get {
                return ResourceManager.GetString("SH_Cls_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;班級系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Integer極限&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;班級名稱&quot;&gt;
        ///		&lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不可重覆。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Uniq&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「班級名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_Cls_FieldValidationRule {
            get {
                return ResourceManager.GetString("SH_Cls_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;ID&quot; Name=&quot;班級系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///	&lt;Field InternalName=&quot;ClassName&quot; Name=&quot;班級名稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;ClassName&quot;/&gt;
        ///  &lt;Field InternalName=&quot;TeacherName&quot; Name=&quot;班導師&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field InternalName=&quot;GradeYear&quot; Name=&quot;年級&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field InternalName=&quot;DepartmentName&quot; Name=&quot;科別&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field InternalName=&quot;GraduationPlan&quot; Name=&quot;課程規劃&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///	&lt;Field InternalName= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_Cls_ImportFieldList {
            get {
                return ResourceManager.GetString("SH_Cls_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DataType=&quot;integer&quot; DisplayText=&quot;課程系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;ID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;課程名稱&quot; Name=&quot;CourseName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DataType=&quot;integer&quot; DisplayText=&quot;科目級別&quot; Name=&quot;SubjectLevel&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;科目名稱&quot; Name=&quot;Subject&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;所屬班級&quot; Name=&quot;ClassName&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學年度&quot; Name=&quot;SchoolYear&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_Course_ExportDescription {
            get {
                return ResourceManager.GetString("SH_Course_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; Required=&quot;True&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Fie [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_S_BulkDescription {
            get {
                return ResourceManager.GetString("SH_S_BulkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DataType=&quot;integer&quot; DisplayText=&quot;學生系統編號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentID&quot; ReadOnly=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;姓名&quot; Name=&quot;Name&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;學號&quot; Identifiable=&quot;True&quot; Name=&quot;StudentNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Identifiable=&quot;True&quot; Name=&quot;IDNumber&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;國籍&quot; Name=&quot;Nationality&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;出生地&quot; Name=&quot;BirthPlace&quot; ShiftCheckable=&quot;True&quot;/&gt;
        ///  &lt; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_S_ExportDescription {
            get {
                return ResourceManager.GetString("SH_S_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;學生系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;此欄位的資料不可重覆。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Uniq&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_S_FieldValidationRule {
            get {
                return ResourceManager.GetString("SH_S_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field DisplayText=&quot;教師系統編號&quot; Name=&quot;TeacherID&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師姓名&quot; Name=&quot;Name&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;暱稱&quot; Name=&quot;Nickname&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;性別&quot; Name=&quot;Gender&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;身分證號&quot; Name=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;聯絡電話&quot; Name=&quot;ContactPhone&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;電子信箱&quot; Name=&quot;Email&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師類別&quot; Name=&quot;Category&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;登入帳號&quot; Name=&quot;SmartTeacherLoginName&quot;/&gt;
        ///  &lt;Field DisplayText=&quot;教師編號&quot; Name=&quot;TeacherNumber&quot;/&gt;
        ///  &lt;Field D [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_T_ExportDescription {
            get {
                return ResourceManager.GetString("SH_T_ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;ValidateRule&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field DataType=&quot;Integer&quot; Name=&quot;教師系統編號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師系統編號」必須是數字。 &quot; ErrorType=&quot;Error&quot; Validator=&quot;Integer極限&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot;String&quot; Name=&quot;教師姓名&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot;/&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「教師姓名」長度必須小於100個文字。&quot; ErrorType=&quot;Error&quot; Validator=&quot;文字100&quot; When=&quot;&quot;/&gt;
        ///    &lt;/Field&gt;
        ///    &lt;Field DataType=&quot; [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_T_FieldValidationRule {
            get {
                return ResourceManager.GetString("SH_T_FieldValidationRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;FieldDescription&gt;
        ///  &lt;Field InternalName=&quot;TeacherID&quot; Name=&quot;教師系統編號&quot; PrimaryKey=&quot;True&quot; UniqueGroup=&quot;PrimaryKey&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Name&quot; Name=&quot;教師姓名&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InsertRequired=&quot;True&quot; InternalName=&quot;Nickname&quot; Name=&quot;暱稱&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;TeacherName&quot;/&gt;
        ///  &lt;Field InternalName=&quot;Gender&quot; Name=&quot;性別&quot;/&gt;
        ///  &lt;Field InternalName=&quot;IDNumber&quot; Name=&quot;身分證號&quot; ShiftCheckable=&quot;True&quot; UniqueGroup=&quot;IDNumber&quot;/&gt;
        ///  &lt;Field InternalName=&quot;ContactP [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SH_T_ImportFieldList {
            get {
                return ResourceManager.GetString("SH_T_ImportFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap studentsPic {
            get {
                object obj = ResourceManager.GetObject("studentsPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap subject_64 {
            get {
                object obj = ResourceManager.GetObject("subject_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap tutorial_fav_64 {
            get {
                object obj = ResourceManager.GetObject("tutorial_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap unlocked {
            get {
                object obj = ResourceManager.GetObject("unlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap world_zoom_64 {
            get {
                object obj = ResourceManager.GetObject("world_zoom_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 一般 {
            get {
                object obj = ResourceManager.GetObject("一般", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 休學 {
            get {
                object obj = ResourceManager.GetObject("休學", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 刪除 {
            get {
                object obj = ResourceManager.GetObject("刪除", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生個人獎懲明細 {
            get {
                object obj = ResourceManager.GetObject("學生個人獎懲明細", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生個人缺曠明細 {
            get {
                object obj = ResourceManager.GetObject("學生個人缺曠明細", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;學籍身分對照表&gt;&lt;Identity Code=&quot;1&quot; Name=&quot;原住民&quot;/&gt;&lt;Identity Code=&quot;4&quot; Name=&quot;身心障礙生&quot;/&gt;&lt;Identity Code=&quot;5&quot; Name=&quot;僑生&quot;/&gt;&lt;Identity Code=&quot;6&quot; Name=&quot;派外人員子女&quot;/&gt;&lt;Identity Code=&quot;7&quot; Name=&quot;蒙藏生&quot;/&gt;&lt;Identity Code=&quot;8&quot; Name=&quot;邊疆生&quot;/&gt;&lt;Identity Code=&quot;9&quot; Name=&quot;港澳生&quot;/&gt;&lt;Identity Code=&quot;10&quot; Name=&quot;體育績優學生&quot;/&gt;&lt;Identity Code=&quot;11&quot; Name=&quot;技藝技能甄審入學學生&quot;/&gt;&lt;Identity Code=&quot;12&quot; Name=&quot;其他&quot;/&gt;&lt;Identity Code=&quot;13&quot; Name=&quot;境外優秀科學技術人才子女&quot;/&gt;&lt;Identity Code=&quot;14&quot; Name=&quot;退伍軍人&quot;/&gt;&lt;Identity Code=&quot;15&quot; Name=&quot;外國學生&quot;/&gt;&lt;Identity Code=&quot;16&quot; Name=&quot;重大災害地區學生&quot;/&gt;&lt;/學籍身分對照表&gt; 的當地語系化字串。
        /// </summary>
        internal static string 學籍身分對照表 {
            get {
                return ResourceManager.GetString("學籍身分對照表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 定期評量班級成績單 {
            get {
                object obj = ResourceManager.GetObject("定期評量班級成績單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 延修 {
            get {
                object obj = ResourceManager.GetObject("延修", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 歷年功過及出席統計 {
            get {
                object obj = ResourceManager.GetObject("歷年功過及出席統計", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 獎懲通知單 {
            get {
                object obj = ResourceManager.GetObject("獎懲通知單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級名條 {
            get {
                object obj = ResourceManager.GetObject("班級名條", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級學生獎懲明細 {
            get {
                object obj = ResourceManager.GetObject("班級學生獎懲明細", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級學生缺曠明細 {
            get {
                object obj = ResourceManager.GetObject("班級學生缺曠明細", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級考試成績單 {
            get {
                object obj = ResourceManager.GetObject("班級考試成績單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級通訊錄 {
            get {
                object obj = ResourceManager.GetObject("班級通訊錄", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 班級點名表 {
            get {
                object obj = ResourceManager.GetObject("班級點名表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 畢業 {
            get {
                object obj = ResourceManager.GetObject("畢業", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 缺曠通知單 {
            get {
                object obj = ResourceManager.GetObject("缺曠通知單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 缺曠週報表 {
            get {
                object obj = ResourceManager.GetObject("缺曠週報表", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 輟學 {
            get {
                object obj = ResourceManager.GetObject("輟學", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 離校 {
            get {
                object obj = ResourceManager.GetObject("離校", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
