//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.1433
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchool.Common
{
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelliSchool.DSA30.Util.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 已在連線狀態，無法執行此動作。 的當地語系化字串。
        /// </summary>
        internal static string ConnectedError {
            get {
                return ResourceManager.GetString("ConnectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未連線成功，但未產生錯誤訊息。 的當地語系化字串。
        /// </summary>
        internal static string ConnectFailNoErrorMessage {
            get {
                return ResourceManager.GetString("ConnectFailNoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未初始化連線資訊，無法進行連線動作。 的當地語系化字串。
        /// </summary>
        internal static string ConnectionInfoNotInitialize {
            get {
                return ResourceManager.GetString("ConnectionInfoNotInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 要求連接時發生未預期的錯誤。 的當地語系化字串。
        /// </summary>
        internal static string ConnectOccureUnknowError {
            get {
                return ResourceManager.GetString("ConnectOccureUnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連接服務(&lt;%ServiceName%&gt;)內部執行錯誤。 的當地語系化字串。
        /// </summary>
        internal static string ConnectServiceError {
            get {
                return ResourceManager.GetString("ConnectServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線到 DSNS 主機錯誤。(&lt;%Url%&gt;) 的當地語系化字串。
        /// </summary>
        internal static string ConnectToDSNSError {
            get {
                return ResourceManager.GetString("ConnectToDSNSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 將 DSA 狀態代碼(StatusCode)轉型成 DSAServerStatus 列舉錯誤，DSA 回傳狀態不存在於 DSAServerStatus 中。 的當地語系化字串。
        /// </summary>
        internal static string ConvertDSAServerStatusError {
            get {
                return ResourceManager.GetString("ConvertDSAServerStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入資訊不正確。 的當地語系化字串。
        /// </summary>
        internal static string CredentialInvalid {
            get {
                return ResourceManager.GetString("CredentialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定的元素不存在。 的當地語系化字串。
        /// </summary>
        internal static string ElementNotFound {
            get {
                return ResourceManager.GetString("ElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可以使用 Null 物件建立物件。 的當地語系化字串。
        /// </summary>
        internal static string ElementNullReferenceNotSupport {
            get {
                return ResourceManager.GetString("ElementNullReferenceNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 XmlDocument 物件中沒有資料。 的當地語系化字串。
        /// </summary>
        internal static string EmptyXmlDocument {
            get {
                return ResourceManager.GetString("EmptyXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從 DSA Application 取得回覆文件錯誤。 的當地語系化字串。
        /// </summary>
        internal static string GetDSAResponseError {
            get {
                return ResourceManager.GetString("GetDSAResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從 HTTP Server 取得 Response 錯誤 的當地語系化字串。
        /// </summary>
        internal static string GetHttpResponseError {
            get {
                return ResourceManager.GetString("GetHttpResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從 HTTP Response 中取出資料串流錯誤。 的當地語系化字串。
        /// </summary>
        internal static string GetHTTPResponseStreamError {
            get {
                return ResourceManager.GetString("GetHTTPResponseStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標頭的名稱不合法。(&lt;%Name%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string HeaderNameNotValidate {
            get {
                return ResourceManager.GetString("HeaderNameNotValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不支援此種 HTTP 方法(&lt;%Method%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string HttpMethodNotSupported {
            get {
                return ResourceManager.GetString("HttpMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 必需是連線狀態才能執行此動作。 的當地語系化字串。
        /// </summary>
        internal static string MustConnected {
            get {
                return ResourceManager.GetString("MustConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可以使用 XmlNodeType.Element 之外的 XmlNode 建立物件。 的當地語系化字串。
        /// </summary>
        internal static string NodeTypeNotSupport {
            get {
                return ResourceManager.GetString("NodeTypeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 物件狀態不正確，請通知開發人員修正此問題。 的當地語系化字串。
        /// </summary>
        internal static string ObjectStatusError {
            get {
                return ResourceManager.GetString("ObjectStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置(Renew) DSA Passport Token 失敗。 的當地語系化字串。
        /// </summary>
        internal static string RenewDSAPassportFail {
            get {
                return ResourceManager.GetString("RenewDSAPassportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置(Renew) Security Token 失敗。 的當地語系化字串。
        /// </summary>
        internal static string RenewSecurityTokenFail {
            get {
                return ResourceManager.GetString("RenewSecurityTokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新要求 SessionID 失敗。 的當地語系化字串。
        /// </summary>
        internal static string RenewSessionIDFail {
            get {
                return ResourceManager.GetString("RenewSessionIDFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 向主機要求 DSAPassport 時產生錯誤！(&lt;%AuthAccessPoint%&gt;) 的當地語系化字串。
        /// </summary>
        internal static string RequestPassportError {
            get {
                return ResourceManager.GetString("RequestPassportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 向 DSA Application 取得 SessionID 失敗。 的當地語系化字串。
        /// </summary>
        internal static string RequestSessionIDFail {
            get {
                return ResourceManager.GetString("RequestSessionIDFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳送「名稱解析」申請文件失敗。 的當地語系化字串。
        /// </summary>
        internal static string ResolveAccessPointNameFail {
            get {
                return ResourceManager.GetString("ResolveAccessPointNameFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主機回傳的文件不符DSA規格(訊息：&lt;%ValidMessage%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string ResponseDocumentInvalidate {
            get {
                return ResourceManager.GetString("ResponseDocumentInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可以使用此類型的 SecurityToken 進行連線動作。 的當地語系化字串。
        /// </summary>
        internal static string SecurityTokenNotSupported {
            get {
                return ResourceManager.GetString("SecurityTokenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 向 DSA Application 要求 SessionID，但並未得到 SessionID。(可能是 DSA Server 不支援 Session 功能) 的當地語系化字串。
        /// </summary>
        internal static string SessionServiceNotSupported {
            get {
                return ResourceManager.GetString("SessionServiceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定的標頭不存在(&lt;%Name%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string SpecialHeaderNotFound {
            get {
                return ResourceManager.GetString("SpecialHeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不支援指定的配置識別項(&lt;%Prefix%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string UriPrefixNotSupport {
            get {
                return ResourceManager.GetString("UriPrefixNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不可以使用 Null 的 XmlDocument 建立物件。 的當地語系化字串。
        /// </summary>
        internal static string XmlDocNullReferenceNotSupport {
            get {
                return ResourceManager.GetString("XmlDocNullReferenceNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Xml 不符合 DSEnvelope 規格：&lt;%Reason%&gt; 的當地語系化字串。
        /// </summary>
        internal static string XmlDocumentNotIsDSDocument {
            get {
                return ResourceManager.GetString("XmlDocumentNotIsDSDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定的 XPath 語法錯誤，找不到指定的元素(&lt;%XPath%&gt;)。 的當地語系化字串。
        /// </summary>
        internal static string XPathSyntaxError {
            get {
                return ResourceManager.GetString("XPathSyntaxError", resourceCulture);
            }
        }
    }
}
